escalation: tuberose
thepeacockproject/Peacock pull request #399
Opened 2024-03-12 07:10 UTC by suanjiansalt

by me. please give it a check at least.

2024-03-12 15:48 UTC, AnthonyFuller requested changes

2024-03-12 15:48 UTC, AnthonyFuller commented on contractdata/BANGKOK/ESCALATION/TUBEROSE/TUBEROSE1.json
> +            "9a89c97d-532b-e8b2-6e34-312470321f2e"
This Gamechanger does not exist.

2024-03-13 00:38 UTC, suanjiansalt commented
And if I get it correctly, the weird blank objective may be caused by gamechangers it uses.

2024-03-13 00:52 UTC, suanjiansalt commented on contractdata/BANGKOK/ESCALATION/TUBEROSE/TUBEROSE1.json
> +            "9a89c97d-532b-e8b2-6e34-312470321f2e"
Updated adapted gamechangers.

2024-03-13 01:10 UTC, AnthonyFuller commented
On Level 1, when pouring the insecticide, it instantly fails. I was wearing the Hotel Staff disguise.

2024-03-13 01:32 UTC, AnthonyFuller commented
Level 2:
![image](https://github.com/thepeacockproject/Peacock/assets/24512050/9f3ad265-5bdf-4b00-b574-888e6cb71a13)

![image](https://github.com/thepeacockproject/Peacock/assets/24512050/8ba88444-ff40-48d8-ab5b-e8a905f53d9d)

2024-03-13 01:33 UTC, AnthonyFuller commented
Also please ensure you are following this [escalation guidelines](https://github.com/thepeacockproject/Peacock/blob/v7/docs/ESCALATION_GUIDELINES.md). I will check this myself, but it would save me some time.

2024-03-13 01:56 UTC, suanjiansalt commented
> Also please ensure you are following the [escalation guidelines](https://github.com/thepeacockproject/Peacock/blob/v7/docs/ESCALATION_GUIDELINES.md).

I checked the guideline (or shall I say that's the rule I follow when making the contract) and the only disobey is in the last contract to kill the woman, it automatically appears in the last position due to activition machanics.

2024-03-13 02:14 UTC, AnthonyFuller commented
> Also many descriptions that don't use full stops, this is to minimize the file size by reusing strings.
That's fine.

Also level 2:
![image](https://github.com/thepeacockproject/Peacock/assets/24512050/3793bb9c-1c4b-4168-a369-17620bf0c420)

2024-03-13 06:38 UTC, riisikumi commented
I can't say anything about the escalation itself, but I'd suggest changing the name – The Trading Tradition sounds a bit dumb imo

2024-03-13 08:39 UTC, suanjiansalt commented
It's called The Ethereal Eruption now. (Maybe dumber?)

2024-03-31 20:32 UTC, AnthonyFuller approved these changes
LGTM. Please PR images into the image pack.

2024-03-31 20:43 UTC, AnthonyFuller commented
Upon further discussion internally, this escalation won't be merged into core. We recommend making it a mod + plugin and release it on Nexus.

2024-03-31 20:43 UTC, closed without merging

2024-03-31 20:51 UTC, RDIL commented
Will just put this here for context as to why I'm not wanting to add this one to core, I think it's an okay escalation, it's well done for your first time making one! There are a few reasons I don't want to add this one to core, namely, we used to have a modded bonus mission in Peacock called Traditions of the Trade by kercyx which played similarly to this escalation, and people did not like it.

I'm not saying this escalation is bad, it's more that I'm not sure if adding an escalation which had a very similar idea to content we already removed is a good idea, just because it might feel too similar.

Appreciate the PR nonetheless! The Hawkes Bay escalation in #402 looks really good and I'm excited to get that one merged!

2024-03-31 23:27 UTC, suanjiansalt commented
> We used to have a modded bonus mission in Peacock called Traditions of the Trade by kercyx which played similarly to this escalation, and people did not like it.
> 
> I'm not saying this escalation is bad, it's more that I'm not sure if adding an escalation which had a very similar idea to content we already removed is a good idea, just because it might feel too similar.
> 

Well in fact that's from which I had an idea to make this escalation. A well-designed level (of course it has a very bad experience, too long and tedious) is quite simply discarded. Of course it's not even my brainchild so I'm just a little bit sorry about that. Certainly I wouldn't say, "Oh, my adaptation would be a thousand times stronger!" but just want something to live even in another forms.

And - of course, I'd say the other "bonus mission" (Lee Hong one) doesn't deserve much sympathy from me because it's so similar to the official escalation.

2024-03-31 23:30 UTC, AnthonyFuller commented
Yeah Lee Hong was removed for that reason too. I did play the escalation, I do recommend making it a mod. You can't add localised lines via a plugin.