feat: Pro1 challenges
thepeacockproject/Peacock pull request #502
Opened 2024-08-08 23:28 UTC by RDIL

## Scope

Add h6's professional mode challenges

## Test Plan

have not yet tested, will soon

## Checklist

-   [ ] I have run Prettier to reformat any changed files
-   [ ] I have verified my changes work

2024-08-10 02:02 UTC, RDIL commented on components/scoreHandler.ts
> +    }
Below this is only logic for committing scores & handling livesplit updates, which we can just ignore.

2024-08-10 02:02 UTC, RDIL commented on components/scoreHandler.ts
> -    // TODO? generate this curve from contractSession.scoring.Settings["timebonus"] somehow
Tried this, it's not possible, the curve is not linear.

2024-08-10 02:02 UTC, RDIL commented on components/2016/legacyProfileRouter.ts
> -        // TODO: HELP! Please DM rdil if you see this
(Vague todo I wrote for myself when realizing how big of a pain pro1 challenges would be)

2024-08-10 22:06 UTC, RDIL commented on components/candle/challengeHelpers.ts
>      locationId: string,
Todo: can we just pass the filter object here?

2024-08-10 22:12 UTC, RDIL commented on components/menuData.ts
> +                    Difficulty: "normal", // FIXME: is this right?
No it isn’t

2024-08-14 22:37 UTC, AnthonyFuller requested changes

2024-08-14 22:37 UTC, AnthonyFuller commented on components/scoreHandler.ts
>      // TODO: For this entire function, add support for 2016 difficulties
We have this now.

2024-08-14 22:37 UTC, AnthonyFuller commented on components/scoreHandler.ts
> +    if (gameVersion === "h1") {
This is here twice?

2024-08-18 02:57 UTC, AnthonyFuller commented on components/scoreHandler.ts
This also sends the `Progression_LevelGain` event to the client to pop mastery achievements on mission end.

2024-08-18 02:59 UTC, RDIL commented on components/scoreHandler.ts
Ref #489

2024-08-18 03:03 UTC, AnthonyFuller approved these changes
LGTM, not experienced the progress bar issue in at least a double digit number of runs now.

EDIT: General Mastery Improvements 🫡

2024-08-19 17:10 UTC, merged