feat: in-game options, flags overhaul
thepeacockproject/Peacock pull request #506
Opened 2024-08-11 15:14 UTC by LennardF1989

Draft PR with WIP logic for an in-game options menu for Peacock (as a plugin, currently).

Also comes with extended flags.ts to feed the right information to the UI, plus logic to allow plugins to register their own flags (example included).

2024-08-11 15:48 UTC, RDIL commented
Lennard I love you this is amazing

2024-08-20 04:06 UTC, AnthonyFuller commented
Just pushed a bit of code which "migrates" the old options file. I just add the flags we just read under the `peacock` section. From my testing it seems like it works. It will be for v8 anyway, so breaking changes are allowed.

2024-08-20 17:39 UTC, LennardF1989 commented
> Just pushed a bit of code which "migrates" the old options file. I add the flags we just read under the `peacock` section. From my testing it seems like it works. It will be for v8 anyway, so breaking changes are allowed.

Awesome - I mostly did the other options.ini file so I could switch between this and other branches, without constantly losing my stuff. But this is the way forward anyway! Great :)

2024-08-20 23:35 UTC, AnthonyFuller commented
My plan for this right now is to override the IOI account portion of the options menu. This will virtually never be removed in an update or changed by mods. It also means it works everywhere. The Peacock tab is cool and all for testing, but moving it into options is better overall.

2024-08-21 00:24 UTC, RDIL commented
what about our evil plans to make everyone require a peacock account to use it /s

2024-08-21 07:38 UTC, LennardF1989 commented
My idea was that plugins could eventually register their own top-level entries in the menu (like the Test one) where they could do whatever they had to for their plugins, not just flags. This could obviously also work under Options :)

On top of that, I think we may need two (or more) cachebuster variables to be able to control when which portion of the menu forcefully updates when. In my initial implementation, whenever yo do something in the UI you are always kicked back to the root of everything because the root-level also updates. But this may or may not be related to the cachebuster at all, but rather the way to ioiaccount response is handled.

2024-08-21 18:09 UTC, AnthonyFuller commented
Yeah, I think the refresh of the menu is due to the `submit-email` forcing it.

One way around this is to store all the changes and do a bulk update by either pressing a "Save" button or by doing it when you exit the category.

> My idea was that plugins could eventually register their own top-level entries in the menu (like the Test one) where they could do whatever they had to for their plugins, not just flags. This could obviously also work under Options :)

Makes sense, we could still do this within options like you said, plugins could have their own menu with a link to a settings page within it (for flags) and then other custom pages.

2024-08-21 19:53 UTC, LennardF1989 commented
Found the issue with the enums, working on a fix.

2024-08-21 21:15 UTC, LennardF1989 commented
The last commit is not in a working state.
- It tries to look for options.json, but it does not exist.
- The logic of the old hub.json is not reimplemented, so `peacock:getAllFlags` is never executed.
- Hitman crashes upon load if the first issue mentioned is fixed.

On top of that, I would really like to have the "Refresh UI" and cache buster data visible when PEACOCK_DEV is set, this really slows down testing changes to the UI.

I've pushed my enum fix either way, but this will need additional work.

2024-08-21 22:14 UTC, AnthonyFuller commented
Just pushed `options.json`, webstorm wasn't tracking it so I didn't realise I hadn't pushed it.

> On top of that, I would really like to have the "Refresh UI" and cache buster data visible when PEACOCK_DEV is set, this really slows down testing changes to the UI. Also a nice excuse to extend the plugin API to be able to add this (along with the old "Test" menu option).

Agreed.

> System is kinda messy, but it works.

Yeah, menu templates get messy fast. The current system for enums is nice since it still shows the option info on the right, giving you context for what each option does.

2024-10-18 15:16 UTC, AnthonyFuller commented
What's stopping this from being merged right now?

2024-10-18 20:20 UTC, LennardF1989 commented
I can give it a test run this weekend to make sure it's functional and doesn't break backwards compatibility.

2024-10-18 23:27 UTC, AnthonyFuller commented
One thing is that it should be moved into core, not a plugin.

2024-10-20 21:03 UTC, RDIL requested changes

2024-10-20 21:03 UTC, RDIL commented on components/flags.ts
> +        Object.keys(defaultSection.flags).forEach((flagKey) => {
Nit: let's make this a for-of loop

2024-10-20 21:03 UTC, RDIL commented on components/profileHandler.ts
> +                        args = querystring.parse(c.substring(commandIndex + 1))
Let's use `URLSearchParams` instead, which isn't deprecated

2024-10-21 22:31 UTC, LennardF1989 commented
Update:
- Moved logic out of plugin to core, exposing hooks and useful functions for plugins
- Performed the requested code changes

Why this is not ready yet (Must):
- Menu navigation is annoying, as changing flags kicks you back to the root.
- Isn't the `ispeacockdev.json` trick always returning true now, even when you are not running as dev? 

Should:
- Needs documentation for plugin developers, specifically `registerFlagSection`, `addCommandMap` and `handleCommand`-hook.

Nice to have:
- Needs some additional functions to make it easy to add your own custom menu files. I plan on restoring my original modal, button and forEach test, by only calling some core functions. But this could be a separate ticket.

2024-10-21 22:34 UTC, LennardF1989 commented on components/commandService.ts
> +            commands.forEach((c) => {
Should be a const-of, I somehow mist this or accidentally reverted it...

2024-10-21 22:34 UTC, LennardF1989 commented on components/commandService.ts
> +// LennardF1989: Do we want to consider string[] because of the use of URLSearchParams?
Yes, no, maybe?

2024-10-21 23:41 UTC, AnthonyFuller commented
> Menu navigation is annoying, as changing flags kicks you back to the root.

I spoke to RDIL about this, he said that it should just save after every option change (like this). Sure, it's annoying, but it means any changes will be reflected instantly instead of a user forgetting to press save or something.

2024-10-22 08:10 UTC, LennardF1989 commented
> > Menu navigation is annoying, as changing flags kicks you back to the root.
> 
> I spoke to RDIL about this, he said that it should just save after every option change (like this). Sure, it's annoying, but it means any changes will be reflected instantly instead of a user forgetting to press save or something.

Agreed, it should immediately change. I was just wondering if there is a way to not reset the menu.

Afaik this happens because the email-endpoint updates the variable, so interesting to see if we can counter that by maintaining a client-side state and not sending back a status-response all the time OR simply remember where the user was in the UI and immediately jump back to that point (similar to what you do with the Freelancer tile that immediately starts it).

But I was out of time yesterday.

2024-10-23 02:44 UTC, RDIL commented on components/commandService.ts
> +// LennardF1989: Do we want to consider string[] because of the use of URLSearchParams?
I'm fine with either, your call

2024-10-29 23:28 UTC, RDIL commented
Since this is blocking in-game roulette's release, and we don't want users to have to use an unofficial PR branch, going to make the decision to merge this in it's current state. We can do follow-ups to improve it, but I think the current implementation is good enough:tm: to ship in an alpha state.

2024-10-29 23:28 UTC, RDIL approved these changes

2024-10-29 23:31 UTC, merged