Implement support for SMF server replacement compatibility
thepeacockproject/Peacock pull request #55
Opened 2022-12-12 04:16 UTC by atampy25

This is currently just so that Cirrus will build it for me, since Peacock fails to build with a series of bizarre errors whenever I try

2022-12-12 04:39 UTC, atampy25 commented
LGTM

2022-12-12 12:57 UTC, AnthonyFuller requested changes
Other than the comment, it LGTM.

2022-12-12 12:57 UTC, AnthonyFuller commented on components/controller.ts
> +            ).lastServerSideStates
You might as well type this properly, a type may already exist for it as we read it for the deployed mods. If it does not, it should be refactored to use a type.

2022-12-12 13:44 UTC, AnthonyFuller commented on components/controller.ts
> +            ).lastServerSideStates
Then see the latter part of my comment.

2022-12-13 03:21 UTC, AnthonyFuller approved these changes
LGTM

2022-12-13 03:22 UTC, merged